### PR TITLE
Make Nginx ssl only

### PR DESCRIPTION
**Pull request by nutterthanos**
Removed Nginx access by http and only allow ssl connections by default.
Edit: Fixed the mistake because I figured out that you still can modify the file in files changed on github in the pr.

### CODE REVIEW

**Comment by Ansuel** [comment]
The fact is that some user will think that the gui is broken

**Comment by nutterthanos** [comment]
But how?

**Comment by Ansuel** [comment]
no redirect from http to https (stock nginx is not compiled with it by default)

**Comment by nutterthanos** [comment]
Oh lol why would it not be compiled by default?

**Comment by Ansuel** [comment]
Mistery they have the lua module but not the redirect

Il Lun 29 Lug 2019, 15:33 nutterthanos <notifications@github.com> ha
scritto:

**Comment by nutterthanos** [comment]
So how are we gonna do this?

**Comment by kevdagoat** [comment]
I would suggest you should have two server blocks, one for http and the other for https.

The http one references a file with a link to the https server.

Toggalability could be implemented by creating two config files and switching between them

**Comment by Ansuel** [comment]
Can you give me an example?

Il Mar 30 Lug 2019, 01:26 Kevdagoat <notifications@github.com> ha scritto:

**Comment by kevdagoat** [comment]
Well, using lua copy commands from the webgui

**Comment by nutterthanos** [comment]
> Well, using lua copy commands from the webgui

But how?

**Comment by Ansuel** [comment]
I actually had an idea
We use ngx.redirect module

Il Ven 2 Ago 2019, 03:42 nutterthanos <notifications@github.com> ha scritto:

**Comment by nutterthanos** [comment]
So we will need to make a package that has that module.

**Comment by Ansuel** [comment]
To use the default nginx redirect we need to compile a package
The ngx.redirect is built in the precompiled nginx (it's part of the lua
module)

Il Sab 3 Ago 2019, 01:36 nutterthanos <notifications@github.com> ha scritto:

**Comment by nutterthanos** [comment]
This is my nginx -V request
nginx version: nginx/1.12.1
built by gcc 5.3.0 (OpenWrt GCC 5.3.0 unknown) 
built with OpenSSL 1.0.2o  27 Mar 2018 (running with OpenSSL 1.0.2s  28 May 2019)
TLS SNI support enabled
configure arguments: --crossbuild=Linux::arm --prefix=/usr --conf-path=/etc/nginx/nginx.conf --add-module=/var/lib/jenkins/swm-wc1/workspace/Build_10/build/openwrt/build_dir/target-arm_cortex-a9_glibc-2.24_eabi/nginx-1.12.1/lua-nginx --with-ipv6 --with-http_ssl_module --without-http-cache --without-pcre --without-http_charset_module --without-http_gzip_module --without-http_ssi_module --without-http_userid_module --without-http_access_module --without-http_auth_basic_module --without-http_autoindex_module --without-http_geo_module --without-http_map_module --without-http_split_clients_module --without-http_referer_module --without-http_rewrite_module --without-http_fastcgi_module --without-http_uwsgi_module --without-http_scgi_module --without-http_memcached_module --without-http_limit_conn_module --without-http_limit_req_module --without-http_empty_gif_module --without-http_browser_module --without-http_upstream_hash_module --without-http_upstream_ip_hash_module --without-http_upstream_least_conn_module --without-http_upstream_keepalive_module --error-log-path=/var/log/nginx/error.log --pid-path=/var/run/nginx.pid --lock-path=/var/lock/nginx.lock --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/lib/nginx/body --http-proxy-temp-path=/var/lib/nginx/proxy --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --with-cc=ccache_cc --with-cc-opt='-I/var/lib/jenkins/swm-wc1/workspace/Build_10/build/openwrt/staging_dir/target-arm_cortex-a9_glibc-2.24_eabi/usr/include -I/var/lib/jenkins/swm-wc1/workspace/Build_10/build/openwrt/staging_dir/target-arm_cortex-a9_glibc-2.24_eabi/include -I/var/lib/jenkins/swm-wc1/workspace/Build_10/build/openwrt/staging_dir/toolchain-arm_cortex-a9_gcc-5.3.0_glibc-2.24_eabi/usr/include -I/var/lib/jenkins/swm-wc1/workspace/Build_10/build/openwrt/staging_dir/toolchain-arm_cortex-a9_gcc-5.3.0_glibc-2.24_eabi/include -Os -pipe -march=armv7-a -mtune=cortex-a9 -fno-caller-saves -Wno-error=unused-but-set-variable -g3 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=soft -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=2 -Wl,-z,now -Wl,-z,relro -fvisibility=hidden -ffunction-sections -fdata-sections -DNGX_LUA_NO_BY_LUA_BLOCK' --with-ld-opt='-L/var/lib/jenkins/swm-wc1/workspace/Build_10/build/openwrt/staging_dir/target-arm_cortex-a9_glibc-2.24_eabi/usr/lib -L/var/lib/jenkins/swm-wc1/workspace/Build_10/build/openwrt/staging_dir/target-arm_cortex-a9_glibc-2.24_eabi/lib -L/var/lib/jenkins/swm-wc1/workspace/Build_10/build/openwrt/staging_dir/toolchain-arm_cortex-a9_gcc-5.3.0_glibc-2.24_eabi/usr/lib -L/var/lib/jenkins/swm-wc1/workspace/Build_10/build/openwrt/staging_dir/toolchain-arm_cortex-a9_gcc-5.3.0_glibc-2.24_eabi/lib -znow -zrelro -Wl,--gc-sections' --without-http_upstream_zone_module

**Comment by nutterthanos** [comment]
nginx version: nginx/1.12.1
built by gcc 5.3.0 (OpenWrt GCC 5.3.0 unknown) 
built with OpenSSL 1.0.2o  27 Mar 2018 (running with OpenSSL 1.0.2s  28 May 2019)
TLS SNI support enabled
configure arguments: --crossbuild=Linux::arm --prefix=/usr --conf-path=/etc/nginx/nginx.conf --add-module=/var/lib/jenkins/swm-wc1/workspace/Build_10/build/openwrt/build_dir/target-arm_cortex-a9_glibc-2.24_eabi/nginx-1.12.1/lua-nginx --with-ipv6 --with-http_ssl_module --without-http-cache --without-pcre --without-http_charset_module --without-http_gzip_module --without-http_ssi_module --without-http_userid_module --without-http_access_module --without-http_auth_basic_module --without-http_autoindex_module --without-http_geo_module --without-http_map_module --without-http_split_clients_module --without-http_referer_module --without-http_rewrite_module --without-http_fastcgi_module --without-http_uwsgi_module --without-http_scgi_module --without-http_memcached_module --without-http_limit_conn_module --without-http_limit_req_module --without-http_empty_gif_module --without-http_browser_module --without-http_upstream_hash_module --without-http_upstream_ip_hash_module --without-http_upstream_least_conn_module --without-http_upstream_keepalive_module --error-log-path=/var/log/nginx/error.log --pid-path=/var/run/nginx.pid --lock-path=/var/lock/nginx.lock --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/lib/nginx/body --http-proxy-temp-path=/var/lib/nginx/proxy --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --with-cc=ccache_cc --with-cc-opt='-I/var/lib/jenkins/swm-wc1/workspace/Build_10/build/openwrt/staging_dir/target-arm_cortex-a9_glibc-2.24_eabi/usr/include -I/var/lib/jenkins/swm-wc1/workspace/Build_10/build/openwrt/staging_dir/target-arm_cortex-a9_glibc-2.24_eabi/include -I/var/lib/jenkins/swm-wc1/workspace/Build_10/build/openwrt/staging_dir/toolchain-arm_cortex-a9_gcc-5.3.0_glibc-2.24_eabi/usr/include -I/var/lib/jenkins/swm-wc1/workspace/Build_10/build/openwrt/staging_dir/toolchain-arm_cortex-a9_gcc-5.3.0_glibc-2.24_eabi/include -Os -pipe -march=armv7-a -mtune=cortex-a9 -fno-caller-saves -Wno-error=unused-but-set-variable -g3 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=soft -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=2 -Wl,-z,now -Wl,-z,relro -fvisibility=hidden -ffunction-sections -fdata-sections -DNGX_LUA_NO_BY_LUA_BLOCK' --with-ld-opt='-L/var/lib/jenkins/swm-wc1/workspace/Build_10/build/openwrt/staging_dir/target-arm_cortex-a9_glibc-2.24_eabi/usr/lib -L/var/lib/jenkins/swm-wc1/workspace/Build_10/build/openwrt/staging_dir/target-arm_cortex-a9_glibc-2.24_eabi/lib -L/var/lib/jenkins/swm-wc1/workspace/Build_10/build/openwrt/staging_dir/toolchain-arm_cortex-a9_gcc-5.3.0_glibc-2.24_eabi/usr/lib -L/var/lib/jenkins/swm-wc1/workspace/Build_10/build/openwrt/staging_dir/toolchain-arm_cortex-a9_gcc-5.3.0_glibc-2.24_eabi/lib -znow -zrelro -Wl,--gc-sections' --without-http_upstream_zone_module

**Comment by nutterthanos** [comment]
No reference to ngx.redirect module in configure arguments

**Comment by Ansuel** [comment]
Ngx.redirect is a function of the lua modulus 100% supported since the
stock gui use it

Il Sab 3 Ago 2019, 02:10 nutterthanos <notifications@github.com> ha scritto:

**Comment by nutterthanos** [comment]
yes so it’s using lua-nginx-module to do it.

**Comment by Ansuel** [comment]
done

**Comment by nutterthanos** [comment]
Thanks

**Pull request closed without merging**
