### PR TITLE
Patch add a2pvfb h045l

### PR DESCRIPTION
**Pull request by tjeh**
#785 FRITZ!Box_7582-07.12
`Broadcom DSL Version A2pvfbH045l`
`Built on 03/15/2019 12:03:13`

### CODE REVIEW

**Comment by FrancYescO** [comment]
do you have also the annex B version ready?

**Comment by tjeh** [comment]
not yet, will add it after testing

**Comment by FrancYescO** [comment]
Why closed?

**Comment by tjeh** [comment]
ok so both drivers are added. I successfully was able to sync with the updated driver.

**Comment by tjeh** [comment]
Is there a style convention for the files (I am using vscode with tabs?)

**Comment by FrancYescO** [comment]
As there is no style convention in the original source we are following this randomness 😄 (btw files are minified in the stable releases)
________________________________

**Pull request merged**
