### PR TITLE
merged internet card from Telstra (shows more infos)

### PR DESCRIPTION
**Pull request by FrancYescO**
image

Show Wan sensing L3 Status
Should show mobile status if enabled
Avoid some duplicated code

### CODE REVIEW

**Comment by Ansuel** [comment]
personally it's a bit useless know the status of the wansensing...

**Comment by FrancYescO** [comment]
Probably your are right... But still better than a white space :)

**Comment by Ansuel** [comment]
pensavo e se invece di l3 le traduciamo in qualcosa di più comprensibile?

**Comment by FrancYescO** [comment]
L'ho tolto proprio..

**Pull request merged**
