### PR TITLE
Fix a few problems with debughelper

### PR DESCRIPTION
**Pull request by kevdagoat**
Removes dev mode.

### CODE REVIEW

**Comment by Ansuel** [comment]
pls don't remove dev mode... i notice some problem running it from the webui

**Comment by kevdagoat** [comment]
What were those problems?

If you want to use dev mode just comment out the line:
/etc/init.d/rootdevice debug

**Comment by Ansuel** [comment]
not a solution, the dev argument was good... 
if i need an extensive debug i can ask to run the command for putty... for gui problem the debug log without rootdevice is sufficent

**Comment by kevdagoat** [comment]
So are you saying that we should remove rootdevice?

**Comment by kevdagoat** [comment]
Readded dev mode

**Comment by kevdagoat** [comment]
Should be ok to merge.

**Comment by FrancYescO** [comment]
@kevdagoat please resubmit

**Comment by kevdagoat** [comment]
What do you mean?


Sent from Mail for Windows 10

**Comment by FrancYescO** [comment]
reopen the same PR as Ansuel done some branch changes and this got automatically closed

**Pull request closed without merging**
