### PR TITLE
Part of #572 add Wiki

### PR DESCRIPTION
**Pull request by Suifu**
Based on #572 add the wiki into a subdirectory [need someone powerful to put it here](https://github.com/Ansuel/tch-nginx-gui/wiki)
regard

### CODE REVIEW

**Comment by Ansuel** [comment]
Can this be merged?  (also can you add [ci skip] to one of the commits?)

**Comment by Ghost9090** [comment]
@Suifu

**Comment by Rondom** [comment]
This is actually not supposed to be merged, I think-

The files in the wiki-directory or this PR are supposed to be added to the top-level directory of the repo `ssh://git@github.com/Ansuel/tch-nginx-gui.wiki.git`

**Comment by FrancYescO** [comment]
Merged https://github.com/Ansuel/tch-nginx-gui/wiki

**Pull request closed without merging**
