### PR TITLE
Update Eco Settings Led Settings Message

### PR DESCRIPTION
**Pull request by flywire**

### CODE REVIEW

**Comment by FrancYescO** [comment]
.po file of translations must be updated when changing translated strings

**Comment by flywire** [comment]
> Add more commits by pushing to the patch-1 branch on flywire/tch-nginx-gui.

Trying to change line 3021 (de-de is lines 3500 and 3504)
https://github.com/Ansuel/tch-nginx-gui/blob/dev/decompressed/gui_file/www/lang/it-it/webui-core.po
https://github.com/flywire/tch-nginx-gui/blob/master/decompressed/gui_file/www/lang/it-it/webui-core.mo

Why the different extensions?

**Comment by FrancYescO** [comment]
look at dev branch not master

**Comment by flywire** [comment]
@FrancYescO - How do I get https://github.com/flywire/tch-nginx-gui/tree/patch-2 and https://github.com/flywire/tch-nginx-gui/tree/patch-3 into this pull request rather than as two additional pull requests?

**Pull request merged**
