### PR TITLE
Update for version 7.15

### PR DESCRIPTION
**Pull request by meyergru**
Updated translatations again

### CODE REVIEW

**Comment by Ansuel** [comment]
love that icon, you will do a commit to add the icon or  i need to add it?

also i would suggest to use the fontawesome code... so that we don't use an extra icon ;)

**Comment by meyergru** [comment]
We could use the fontawesome directly, but alle the other buttons are icons...

**Comment by Ansuel** [comment]
umm no only 3 of them are icons other are font awesome icon 

anyway i think i will convert all to fontawesome 5...

**Comment by meyergru** [comment]
There you go, but it is FA 4.7, not 5.

**Comment by meyergru** [comment]
I saw that the repo version is older than the repo version and presumably your local version.

So, if you update the icons yourself and do the button, please remember to include the new DE-DE translations.

**Comment by Ansuel** [comment]
sure ;)

**Pull request merged**
