### PR TITLE
Improvements in DE translations

### PR DESCRIPTION
**Pull request by reschandreas**
I added the uncompiled language files with the file-extension .po for easier usage and maintenance. Furthermore I made some edits for the german phrasing of some of the translations

### CODE REVIEW

**Comment by Ansuel** [comment]
Does plain .po file works?

**Comment by reschandreas** [comment]
I converted the existing .mo files back to the editable .po format using [this site](https://ezgif.com/mo-to-po) and edited and compiled them with [poeditor](https://poedit.net/). I have no technicolor device for testing purposes available, but since I also recompiled the italian translations with this editor and that step resulted in no differences, I suppose that it should work.

**Comment by Ansuel** [comment]
we need to test if the gui is able to read plain .po file instead of .mo

**Comment by reschandreas** [comment]
It doesn't need to do that since the .mo files are still available in the same path. The .po files are just there to provide an easy and fast way to change/add translations.

**Comment by Ansuel** [comment]
Umm ok but the GUI will load the .no file then the changes to the po will
not be displayed

Il Ven 26 Ott 2018, 15:06 reschandreas <notifications@github.com> ha
scritto:

**Comment by reschandreas** [comment]
It's not an instant change. When you have a problem with the translations you simply edit the .po file and after you are done you compile the .po file into a .mo file (this can be done in the terminal or with the program I used, stated above) then you simply switch the old .mo file with the new one and the gui should be updated.

I suppose that that's the way @meyergru has done it until now, but with the source files (.po) in this repository, everybody can do it.

**Comment by meyergru** [comment]
Yes, I usually scan all .lua and .lp files for translations pattern with a script. After that, I use msgmerge to add the new, still empty translations to the old .po files. Once I have added the new translations, I recompile all .po to .mo and create a pull request.

You can extract my .po files from the .mo - nothing magic.

**Comment by Ansuel** [comment]
Can you share this script ? It would be very usefull

Il Ven 26 Ott 2018, 17:10 meyergru <notifications@github.com> ha scritto:

**Comment by meyergru** [comment]
Sure. Here is my folder with the .po, .mo, a script and the program to extract the translations from Lua. Mostly self-explaining, I hope.

[de-de.zip](https://github.com/Ansuel/tch-nginx-gui/files/2519999/de-de.zip)

**Comment by Ansuel** [comment]
@reschandreas can you rework this pull request?

**Comment by reschandreas** [comment]
@Ansuel What do you mean?
@meyergru So I basically did the same thing, I just edited some of your translations that I thought could be phrased differently
@FrancYescO It would be easier for the developement process if the source files were available at any time.

**Comment by FrancYescO** [comment]
oh surely if it does not impact on speed

**Comment by FrancYescO** [comment]
btw you need to repush the files to get these merged as they are in conflicts with the latest commit of the repo

**Comment by Ansuel** [comment]
@reschandreas the gui now use po file directly... We don't need to compile them now...

**Comment by reschandreas** [comment]
@Ansuel Cool! Will my translations still be merged into the master branch?

**Comment by FrancYescO** [comment]
@reschandreas you have to fix conflicts or he cannot merge

**Pull request merged**
