### PR TITLE
Support for Telstra Smartmodem (Gen1)

### PR DESCRIPTION
**Pull request by kevdagoat**
#627 

Adds images and fixes gateway.lp

### CODE REVIEW

**Comment by Ansuel** [comment]
Can i merge this ?

**Comment by FrancYescO** [comment]
image should be optimized 300kb are a little too much ( https://tinypng.com/ ) and probably better to find one in a different angulation and with trasparent background

**Comment by Ansuel** [comment]
also pls rebase

**Comment by kevdagoat** [comment]
@francyesco Good luck finding an image!

**Comment by Ansuel** [comment]
@kevdagoat rebase and use the new lua file model_helper

**Comment by kevdagoat** [comment]
Ok????

**Comment by Ansuel** [comment]
suppressed by 14a2c9be952bed6fbda4b2de1ca79921442c4af0

**Pull request closed without merging**
