### PR TITLE
Add LuCI Install Scripts to /usr/share/transformer/scripts

### PR DESCRIPTION
**Pull request by kevdagoat**
Allows automated install of @nutterpc 's tg-luci GUI for older Technicolor modems.
I don't have a clue on how to integrate this into the web interface so I will leave that to somebody else unless someone can show me.

### CODE REVIEW

**Comment by Ansuel** [comment]
script for install luci are already present... 
actually i don't really like the install script as it destroy the stock gui...

will adds some update to the install luci script (any update to the ports stats?)

**Comment by kevdagoat** [comment]
This is for @nutterpc ‘s LuCI GUI for the TG799/800.

It does not destroy the stock GUI. It configures LuCI to run on port 9080

The port stats is completed but the cards.lp page is broken on mine so can’t test. Will upload though

Sent from Mail for Windows 10

**Comment by Ansuel** [comment]
can you tell me modem compatible?

**Comment by Ansuel** [comment]
Can you test latest version ?

**Comment by nutterpc** [comment]
It's not yet compatible with the TG800. But the TG789/799 yes

**Comment by Ansuel** [comment]
are you sure ? tg800 should be arm right? then the dga package should works just fine... 

tg789 and tg799 is mips ?

**Comment by nutterpc** [comment]
Thats of the packages I did though Ansuel

**Comment by Ansuel** [comment]
someone with tg800 should try dga luci...

**Comment by nutterpc** [comment]
I've also got 2 spare TG789VAC-V2 here now. One is going to a mate, other i'm keepin, so will load both LUCI & tch-nginx-gui on it

**Comment by kevdagoat** [comment]
Have you already done this???
image
image

**Comment by kevdagoat** [comment]
Looks like you have :)
`luci_install_tg799() {
	curl -k -L https://raw.githubusercontent.com/nutterpc/tg-luci/master/install.sh --output /tmp/install.sh
	chmod +x /tmp/install.sh
	/tmp/install.sh
}

`

**Comment by FrancYescO** [comment]
In 8.8.34 789vac Luci Appear as extension not installed but is not possible to install it opening the modal (there is only telstra)

**Comment by kevdagoat** [comment]
Will have a look for you

**Pull request closed without merging**
