### PR TITLE
Overhaul README

### PR DESCRIPTION
**Pull request by kevdagoat**
Add a few more features and updated images

### CODE REVIEW

**Comment by FrancYescO** [comment]
remove old version screenshot 

move screenshot on bottom / move up "If you find a bug..."

**Comment by kevdagoat** [comment]
looks all good to merge

**Comment by FrancYescO** [comment]
wan ip censure

**Comment by Ansuel** [comment]
@kevdagoat can you add the link to the build repository ?

**Comment by kevdagoat** [comment]
Where is that located?

**Comment by FrancYescO** [comment]
https://github.com/Ansuel/gui-dev-build-auto

**Comment by kevdagoat** [comment]
Ok

**Comment by Ansuel** [comment]
anyway that wiki on whirlpool  is huge but no quote on my gui or dga 4130 or 4132 :( sad...

**Comment by kevdagoat** [comment]
I only know one person that has one in aus, so if you want yo can sign up and update the wiki

**Comment by flywire** [comment]
> anyway that wiki on whirlpool is huge but no quote on my gui ...

It's actually the first think described which is not just a link - `1.3 Try a highly modified and universal version of the GUI`.

I agree the instructions suck for Aussies and not helped with lack of image support. As @kevdagoat said - feel free to update the wiki.

**Comment by flywire** [comment]
@kevdagoat

Dosens of xDSL Stats -> Dozens ...
remove full stops after points
attach a photo -> attach an image

Why the DSLAM errors in the images?

**Comment by kevdagoat** [comment]
> Dosens of xDSL Stats -> Dozens ...
remove full stops after points
attach a photo -> attach an image

Ok

> Why the DSLAM errors in the images?
I'm on an older version

**Comment by kevdagoat** [comment]
All good

**Comment by flywire** [comment]
Dosen - German, plural of Dose ;)

**Comment by FrancYescO** [comment]
i just want to see different screenshots not showing a public IP and with no "path not found" issue

**Comment by flywire** [comment]
[Basic installation instructions for the latest Stable release:](https://github.com/Ansuel/tch-nginx-gui#basic-installation-instructions-for-the-latest-stable-release)

Points to dev not stable - should be fixed.

**Pull request merged**
