### PR TITLE
Add more secure reset into rootdevice

### PR DESCRIPTION
**Pull request by kevdagoat**
It is also not a good idea to remove everything except /etc

### CODE REVIEW

**Comment by flywire** [comment]
1. Agree something is needed but can we be confident this is a solution? (It would be no good if the next action filled it.)
2. Is it more than 97% or 96%?

**Comment by FrancYescO** [comment]
whats wrong with the already present reset commands (ignoring the % threshold)? 
1) the partition is not called `rootfs_data` on all modem so this cannot be hardcoded.
2) `mtd erase -r` will reboot the modem on exec so all commands executed later are useless.

**Comment by flywire** [comment]
> 1. the partition is not called `rootfs_data` on all modem so this cannot be hardcoded.

`/dev/mtd2` ??

**Comment by Ansuel** [comment]
Well etc is where the rootdevice is preset also in etc there should be only configuration file... The biggest file you can find should be the xdsl driver
Also it detects when is greater than 96 (so from 97 to 100 will reset)

**Comment by FrancYescO** [comment]
> > 1. the partition is not called `rootfs_data` on all modem so this cannot be hardcoded.
> 
> `/dev/mtd2` ??

a way to get the name of the partition to reset is already in the rootedevice script `df /overlay | sed -n 2p | awk {'{print $1}'}` ... but i'm still confused on WHY this PR is needed.

**Comment by kevdagoat** [comment]
I will remove/substitute rootfs_data

If you remove everything except /etc it does exactly the same thing as firstboot and jffs2reset

**Comment by kevdagoat** [comment]
The point is that there are now less lines, you could call it “Code Optimisation” 😂

**Comment by FrancYescO** [comment]
afaik jffs2reset (aka firstboot on tch modem, so why should call it 2 times ?!) will not preserve /etc (..root).
also jffs2reset will simply fail when the fs is full, the only wayout is mtd erase, that with the -r flag is good enought to get a recovery, no jffs2reset or firstboot cmd needed.

i still see nosense in this PR.

**Comment by kevdagoat** [comment]
To be honest the remove everything except /etc is useless as it does the same as mtd erase

**Comment by FrancYescO** [comment]
> To be honest the remove everything except /etc is useless as it does the same as mtd erase

No.
Not removing /etc from the overlay will do exactly what is wrote in the comments: save root access (and configs...) if this try fails, will just wipe everything to get a working device also with no root.

**Pull request closed without merging**
