### PR TITLE
Allow changing of WiFi tx power

### PR DESCRIPTION
**Pull request by kevdagoat**
#492

### CODE REVIEW

**Comment by Ansuel** [comment]
little dubious about the wifi power %

**Comment by kevdagoat** [comment]
That was from Telstra Stock

**Comment by kevdagoat** [comment]
May as well use dBm

**Comment by kevdagoat** [comment]
*dBm

**Comment by kevdagoat** [comment]
Any news @Ansuel

**Comment by kevdagoat** [comment]
Any news again?

**Comment by Ansuel** [comment]
also adds +1 +2 +3 +4 +5 +6 options

**Comment by kevdagoat** [comment]
Ready to commit? Ideally in future we could use wifi power based on the locale of the modem.

**Comment by Ansuel** [comment]
@kevdagoat can you add to the table  +1 +2 +3 +4 +5 +6 ???

**Comment by kevdagoat** [comment]
@Ansuel Thought you already did that?

**Pull request merged**
