### PR TITLE
Fix Sysupgrade erroring

### PR DESCRIPTION
**Pull request by kevdagoat**
`/sbin/sysupgrade: .: line 3: can't open '/lib/functions/system.sh'`

#588 

Congrats on 1000 commits!!

### CODE REVIEW

**Comment by FrancYescO** [comment]
how can be copied from /rom if script is not present in the firmware?

**Comment by kevdagoat** [comment]
It appears to be present on most firmwares

**Comment by kevdagoat** [comment]
Including mine

**Comment by FrancYescO** [comment]
not were is erroring..

**Comment by kevdagoat** [comment]
Where do you think then 😊

Sent from Mail for Windows 10

**Comment by kevdagoat** [comment]
Added if statement and moved to existing function

**Comment by Ansuel** [comment]
i added the check in the sysupgrade script :( 

the problem is that in some very old build there were no system.sh so we need to check it does exist end skip if not

**Comment by kevdagoat** [comment]
Ok then

**Pull request closed without merging**
