### PR TITLE
Allow to override PPPoE discovered DNS

### PR DESCRIPTION
**Pull request by FrancYescO**
image

### CODE REVIEW

**Comment by Ansuel** [comment]
why use or validation for dnsserver? (gOV)

**Comment by FrancYescO** [comment]
was the only way i found to have also empty value...

**Comment by Ansuel** [comment]
you need to create a dedicated validator... actually i should add it to post_helper...  just wait the next commit

**Comment by FrancYescO** [comment]
But actually is just working as intended 😅

Btw gO stay for Optional not Or

**Comment by Ansuel** [comment]
actually you are right ahaha (and also it's the first time that i notice OptionalValidation my bad...)

**Pull request merged**
