### PR TITLE
English Enhancement pull request #1

### PR DESCRIPTION
**Pull request by kevdagoat**
Modified 6 files.

Will do multiples of these.

### CODE REVIEW

**Comment by FrancYescO** [comment]
https://github.com/Ansuel/tch-nginx-gui/issues/311#issuecomment-433836313 i close the issue, discussion continue here, don't forget to sync .po files or this cannot be merged

**Comment by kevdagoat** [comment]
@FrancYescO You will have to merge this request as if I do a big one, there will be many conflicts with the base branch and it will overwrite the changes that ansuel and others have done

**Comment by FrancYescO** [comment]
No problem to solve conflicts, but this cannot be merged until all .po files are synced with all the new strings

**Comment by kevdagoat** [comment]
Ok, will look at the .po files

**Comment by kevdagoat** [comment]
I have a better idea...

One folder and associated .po files per pull request

**Pull request closed without merging**
