### PR TITLE
Better alignment for GPON values

### PR DESCRIPTION
**Pull request by brusarp**

### CODE REVIEW

**Comment by FrancYescO** [comment]
Avoid inline css otherwise other themes get broken, we should just copy the (code)style from the xDSL modal (and probably choose a better icon)

**Comment by brusarp** [comment]
Ok, I'll try to do something

**Comment by FrancYescO** [comment]
you don't need to open a new PR for edits, you can just push to your branch to get edits added here ;)

**Comment by brusarp** [comment]
Oh, ok... I'm a newbie on GitHub's procedures... ;-)

**Comment by brusarp** [comment]
And also... Isn't better that someone check what I did before I push it? Or someone always check it?

**Comment by FrancYescO** [comment]
accepting this PR = check done

**Comment by brusarp** [comment]
ok, I understand...

**Pull request closed without merging**
