### PR TITLE
DebugHelper Script

### PR DESCRIPTION
**Pull request by kevdagoat**
When run it will assemble data and generate a .tar.gz file containing it 

More info and file samples:
#327

### CODE REVIEW

**Comment by FrancYescO** [comment]
shabang must be in the first line.
on execution finished probably is better to put the tar directly in /tmp removing the folder used to assemble infos

**Comment by FrancYescO** [comment]
and what about a more compressed date with also H and M ... like `date +%Y-%m-%d`

**Comment by Ansuel** [comment]
@kevdagoat pls update this script with the suggestions...

also you should add some info to the index page about this

**Comment by Ansuel** [comment]
also i have this when i run it

root@modemtim:/tmp# ./generate-debug-file.sh
uci: Entry not found
ash: help: unknown operand
DebugHelper: DebugHelper Started! Run debug help for commands.
DebugHelper: Removing directory /tmp/2018-11-17-DebugHelper/* to prevent duplicates
DebugHelper: Creating dir
DebugHelper: Gathering device info...
ash: get: unknown operand
DebugHelper: Scanning for log errors...
DebugHelper: Listing processes...
DebugHelper: Scanning /etc/config directory...
ash: dev: unknown operand
DebugHelper: Running rootdevice script in debug mode. This will take ~35sec...
DebugHelper: Tarring File...
DebugHelper: All Done! Zipped file can be found in /tmp/2018-11-17-DebugHelper/. The name of it is DebugHelper2018-11-17.tar.gz.


and i would suggest to remove the dir when the tar is created and place it in /tmp directly

**Comment by kevdagoat** [comment]
It should suppress all errors?!!

**Comment by Ansuel** [comment]
anyway that error should be fixed...

**Pull request merged**
