### PR TITLE
Bulletproof xDSL status

### PR DESCRIPTION
**Pull request by kevdagoat**
Enlighten issue #547

### CODE REVIEW

**Comment by FrancYescO** [comment]
better to use the same logic everywhere (= just steal the logic from standard cards)

**Comment by kevdagoat** [comment]
I thought we were creating an improved version of the GUI ;)

**Comment by FrancYescO** [comment]
So don't put status like DSL up but no speed as it is an incongruence :D

The path used in cards seems more reliable

**Comment by kevdagoat** [comment]
Ok will edit that in tomorrow

**Pull request closed without merging**
