### PR TITLE
Transmission/Amule/Aria2 restart trigger

### PR DESCRIPTION
**Pull request by capriele**
closes: https://github.com/Ansuel/tch-nginx-gui/issues/1079
closes: https://github.com/Ansuel/tch-nginx-gui/issues/1078
Transmission/Amule/Aria2 restart trigger è rpc_whitelist

### CODE REVIEW

**Comment by FrancYescO** [comment]
lo script hotplug per il restart di transmission forse è meglio contenga qualche check in più per evitare di riavviarlo quando si inserisce una seconda usb che magari non c'entra nulla con transmission

**Comment by capriele** [comment]
Something like that?
```bash
#!/bin/sh
usb_count=$(find /tmp/run/mountd/ -mindepth 1 -maxdepth 1 -type d | wc -l)
if [ "$usb_count" -le "1" ]; then
    /etc/init.d/transmission restart
fi
```

**Comment by FrancYescO** [comment]
mhh yes or probably just a check for an if exist transmission folder on the mounted usb drive (should be an argument of hotplug script called)

**Comment by FrancYescO** [comment]
`-d /tmp/run/mountd/$DEVNAME/sharing/transmission` idk if is correct but something like this (hopefully it is already mounted when script is called)

**Comment by capriele** [comment]
> 
> 
> mhh yes or probably just a check for an if exist transmission folder on the mounted usb drive (should be an argument of hotplug script called)

Ok, Is there a way to detect the latest mounted usb device?

**Comment by capriele** [comment]
This should be what you are searching for...

**Comment by FrancYescO** [comment]
rethinking about this, probably i've introduced a misleading behaviour: restart will be not triggered on unmount (as the path does not exist) so transmission will continue to download to the "unmounted" path

**Comment by capriele** [comment]
> rethinking about this, probably i've introduced a misleading behaviour: restart will be not triggered on unmount (as the path does not exist) so transmission will continue to download to the "unmounted" path

Yes, this could happen. Furthermore `$DEVNAME` it is not equal to `sda1`.

**Comment by capriele** [comment]
@FrancYescO the merged script is wrong:
could this be a valid alternative?
```
        #!/bin/sh
        last_usb=$(ls -t /dev/sd* | tail -n 1)
        last_usb=${last_usb#"/dev/"}
        usb_count=$(find /tmp/run/mountd/ -mindepth 1 -maxdepth 1 -type d | wc -l)
        if [ "$usb_count" == "0" ]; then
            /etc/init.d/transmission restart
        elif [ -d "/tmp/run/mountd/$last_usb/sharing/config/transmission" ]; then
            /etc/init.d/transmission restart
        fi
```

**Comment by FrancYescO** [comment]
https://openwrt.org/docs/guide-user/base-system/hotplug#block
whats the value of `$DEVNAME`? probably it should be used for the /mnt path

the other best bahaviour should be if action == remove && DEVNAME in transmission config > stop transmission

**Comment by capriele** [comment]
> 
> 
> https://openwrt.org/docs/guide-user/base-system/hotplug#block
> whats the value of `$DEVNAME`? probably it should be used for the /mnt path
> 
> the other best bahaviour should be if action == remove && DEVNAME in transmission config > stop transmission

Actually on my device $DEVNAME is equal to: `bus/usb/001/022`

**Pull request merged**
