### PR TITLE
Add mmpbx Stats tile.

### PR DESCRIPTION
**Pull request by kevdagoat**
Still under some development.
image

### CODE REVIEW

**Comment by Ansuel** [comment]
Why not?

Il Sab 15 Set 2018, 12:19 Kevdagoat <notifications@github.com> ha scritto:

**Comment by kevdagoat** [comment]
no idea on creating tables :)

**Comment by Ansuel** [comment]
Mhhh so a card with a table that show WiFi ap?

Il Sab 15 Set 2018, 12:31 Kevdagoat <notifications@github.com> ha scritto:

**Comment by kevdagoat** [comment]
yep

**Comment by kevdagoat** [comment]
any way to create heading for these cards:
function or something??

**Comment by Ansuel** [comment]
what do you mean heading?

**Comment by Ansuel** [comment]
if you mean a table you can see the device info card

**Comment by kevdagoat** [comment]
On the modals there is like a title with a line underneath that:

Hello
————————————————————————-
Any chance of miniaturising that?

**Pull request merged**
